spring:
  application:
    name: common  # 确保这个名称不为空
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos 服务器地址
        service: ${spring.application.name}  # 使用 spring.application.name 作为服务名
      config:
        server-addr: 127.0.0.1:8848  # Nacos 配置服务器地址
        file-extension: yaml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
